<?php
/**
 * ModuleProvider.php
 * Created by: trainheartnet
 * Created at: 8/28/20
 * Contact me at: longlengoc90@gmail.com
 */

namespace AluCMS\Notification\Providers;

use Illuminate\Support\ServiceProvider;

class ModuleProvider extends ServiceProvider
{
    public function boot()
    {
        $this->loadViewsFrom(__DIR__.'/../../resources/views', 'notification');
        $this->loadTranslationsFrom(__DIR__.'/../../resources/lang', 'notification');

        $this->loadMigrationsFrom(__DIR__.'/../../database/migrations');
    }

    public function register()
    {
//        parent::register(); // TODO: Change the autogenerated stub
        $this->app->register(RouteProvider::class);
        $this->app->register(HookProvider::class);
    }
}
