export const CHANGE_GAME_TYPE = 'CHANGE_GAME_TYPE'
export const CHANGE_GAME_SUB_TYPE = 'CHANGE_GAME_SUB_TYPE'
export const PICK_NUMBER = 'PICK_NUMBER'
export const REMOVE_PICKED_NUMBER = 'REMOVE_PICKED_NUMBER'
