<?php
/**
 * ModuleProvider.php
 * Created by: trainheartnet
 * Created at: 9/19/20
 * Contact me at: longlengoc90@gmail.com
 */


namespace AluCMS\Post\Providers;

use Illuminate\Support\ServiceProvider;

class ModuleProvider extends ServiceProvider
{
    public function boot()
    {
        $this->loadViewsFrom(__DIR__.'/../../resources/views', 'post');
        $this->loadMigrationsFrom(__DIR__ . '/../../database/migrations');
        $this->loadTranslationsFrom(__DIR__.'/../../resources/lang', 'post');
    }

    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }
}
